"""User configuration for mm-cli."""

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "mm-cli"
CONFIG_FILE = CONFIG_DIR / "config.toml"


@dataclass
class Config:
    """User configuration for mm-cli."""

    transfer_category: str = ""
    excluded_groups: list[str] = field(default_factory=list)


def load_config(path: Path | None = None) -> Config:
    """Load user configuration from TOML file.

    Args:
        path: Optional override path for testing. Defaults to ~/.config/mm-cli/config.toml.

    Returns:
        Config with values from file, or defaults if file doesn't exist.
    """
    config_path = path or CONFIG_FILE

    if not config_path.exists():
        return Config()

    try:
        with config_path.open("rb") as f:
            data = tomllib.load(f)
    except (tomllib.TOMLDecodeError, OSError):
        return Config()

    return Config(
        transfer_category=data.get("transfer_category", ""),
        excluded_groups=data.get("excluded_groups", []),
    )


def write_config(config: Config, path: Path | None = None) -> Path:
    """Write configuration to TOML file.

    Args:
        config: Configuration to write.
        path: Optional override path for testing. Defaults to ~/.config/mm-cli/config.toml.

    Returns:
        Path to the written config file.
    """
    config_path = path or CONFIG_FILE
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# mm-cli configuration",
        "# Generated by 'mm init' — edit manually or re-run 'mm init'",
        "",
        "# Category name used for internal transfers (between own accounts)",
        "# Leave empty or omit if you don't use a transfer category",
        f'transfer_category = "{config.transfer_category}"',
        "",
        "# Account groups to exclude when using --active flag",
        "# Leave empty or omit if you don't want to exclude any groups",
        _format_toml_string_list("excluded_groups", config.excluded_groups),
        "",
    ]

    config_path.write_text("\n".join(lines), encoding="utf-8")
    return config_path


def _format_toml_string_list(key: str, values: list[str]) -> str:
    """Format a list of strings as a TOML array."""
    if not values:
        return f"{key} = []"
    items = ", ".join(f'"{v}"' for v in values)
    return f"{key} = [{items}]"
